version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Vfg6Kh9jeHD9Z!L
      MYSQL_DATABASE: brizer
      MYSQL_USER: brizer
      MYSQL_PASSWORD: Vfg6Kh9jeHD9Z!L
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  hospital:
    container_name: hospital
    image: hospital
    build: docker
    ports:
      - "8080:8080"

volumes:
  mysql-data:
    driver: local